services:
  redis:
    image: redis/redis-stack:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
      - "8001:8001"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - app-network
  pft-backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: pft-system:latest
    container_name: pft-backend
    restart: always
    ports:
      - "9090:9090"
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy  # Wait for Redis to be healthy
    networks:
      - app-network
networks:
  app-network:
    driver: bridge